### ISSUE TITLE
Avatar does not show

### ISSUE THREAD

**Issue by jessemillar** [NoiSek/Aether#14]
I've tried the `.face` method and the `/var/lib/AccountsService/users/<youraccountname>` method and no avatar shows. Without changes to `/var/lib/AccountsService/users/<youraccountname>` or making a `.face` file, the default astronaut image also doesn't show up.

Installed via AUR.

It's a shame because this is easily the prettiest theme available for lightdm.

**Comment by NoiSek** [comment]
The actual grabbing of the avatar is handled by LightDM rather than the theme itself, so I don't think that I can really address this if the user itself still functions correctly. 

What file format is the avatar that you're trying to use?

Going off of the [LightDM documentation](https://wiki.archlinux.org/index.php/LightDM#Changing_your_avatar) it seems possible that it only accepts `.png` files.

**Comment by jessemillar** [comment]
I'm using a .png in all cases and I do have `accountservice` installed. Still nothing. If it really is a LightDM problem, is there any way to make your theme smart enough to handle the error by at least displaying the default astronaut? A glitchy, blank circle doesn't look super great. 
![photo mar 17 8 48 18 am](https://cloud.githubusercontent.com/assets/4627837/24048659/2e626d88-0aef-11e7-87cb-2110924e3f5c.jpg)

**Comment by NoiSek** [comment]
You should be able to revert to the default astronaut by removing the `.face` file (or `.face.icon`) in your home directory and deleting any references to `icon` in `/var/lib/AccountsService/users/<youraccountname>`, there's no currently implemented way to override it otherwise. The theme just renders the path that it is given by LightDM.

It would appear that your issue is identical to [this person's issue](https://github.com/Antergos/web-greeter/issues/98#issuecomment-269121080) from not too long ago. Based on that, it seems more that there is either a permissions issue or a hardware rendering issue with certain versions of LightDM.

Just for diagnosis:

- Do you have the same issue when using another theme?
- Are there any errors within your `/var/log/lightdm/seat0-greeter.log` ?

All that I can suggest in the meantime is that you upgrade your LightDM version to the latest and try switching the avatar path to rule out permissions issues. The latest version of the theme (released yesterday on the AUR) also allows you to hide the avatar entirely via the settings dialogue if you wished to sidestep the problem entirely.

**Comment by carl03q** [comment]
Solved with moving the image inside the theme folder

**Comment by yawpitch** [comment]
This issue was closed with no actual solution except for a brief mention of moving the image inside the "theme" folder ... which theme folder?

I've got exactly the same issue, no obvious permissions problem, no .face file or icon set in accountsservices, accountservices installed ... but the fallback icon doesn't appear, exactly as per trhe above.

**Comment by michaelKurowski** [comment]
Same. Could you provide an explaination? @carl03q

**Comment by franciscocpg** [comment]
I was having the same problema and solved it by setting the image using the `mugshot` package.

I'm using Antergos Linux with XFCE.

**Comment by codeitlikemiley** [comment]
reason this is happening and not showing an avatar even the default
because the path is wrongly type when you install it on AUR 
/var/lib/AccountService --- Missing `s`
should be 
/var/lib/AccountsService

**Comment by Breach-Candy** [comment]
Personally, I just replaced avatar-background.png with my .face and renamed it.

**Comment by moraisaugusto** [comment]
since I installed this theme the default astronaut avatar doesn't t show for me. I tried to save a personal image in `$HOME/.face` but it doesn't work too. 

My solution was save the `png` directly on `/var/lib/AccountsService/icons/` and I had to change  the `/var/lib/AccountsService/users/$USERNAME` file.
```
[User]
Session=i3
XSession=i3
Icon=/var/lib/AccountsService/icons/$USERNAME.png
SystemAccount=false
```
This solved the problem for me.

**Comment by Alarg** [comment]
Just want to contribute:
I'm using KDE Plasma 5. The solution was to just download a JPEG picture, convert it to PNG using Gwenview, and use KDE's User manager to add the avatar. It might work with a JPEG picture but I didn't try it. No other solution including mod 644 and /icons/ and /users/ worked, strangely.
