### ISSUE TITLE
Hex colour value input disappears randomly

### ISSUE THREAD

**Issue by sjclayton** [NoiSek/Aether#26]
Not sure if you're aware already... but if you open the Style section of the settings dialog and go to pick a colour. If you start entering a hex value, it just randomly switches to RGBA or HSLA and does not allow you to input your hex colour code and when you try to click the up or down arrow to go back to hex value it's no longer available as an option. 

This is highly frustrating as some colours I'd rather set via hex value.

**Comment by NoiSek** [comment]
This has actually been a longtime issue with the color picker library, it's good that you've brought it up again because it seems that it has been mostly fixed upstream in the meantime (there are still issues with the percentage symbols when editing HSL values).

I've pushed an [update that fixes this issue](https://github.com/NoiSek/Aether/releases/tag/v2.0.1). Package has also been updated on the AUR as normal.
