### ISSUE TITLE
error detected in theme - console error: undefined is not an object (e.session.key)

### ISSUE THREAD

**Issue by KaytonFletcher** [NoiSek/Aether#65]
On reboot into arch, dialog popup saying there is an error in theme, providing options to load fallback or cancel. I enabled debugging for lightdm and for webkit2. The error logged in seat0-greeter.log is

*CONSOLE ERROR TypeError: undefined is not an object (evaluating 'e.session.key')*

XServer reports no errors with nvidia graphics driver. And lightdm loads the default theme fine when clicked on the error popup.

**Comment by NoiSek** [comment]
Given that those values are provided by `lightdm`, I can't really speak to the root cause there. My best guess is that it's failing to find your initial session: https://github.com/NoiSek/Aether/blob/441e54bf6b42f70c02478d9c173f72ebc9d96b47/src/js/Logic/SystemOperations.js#L51-L59

Extrapolating from that, it's possible you have a default session set that isn't valid. See: https://askubuntu.com/a/62836

**Comment by KaytonFletcher** [comment]
Thank you for your quick response! I forgot to set the user-session in lightdm's config to i3. Such a silly mistake that took me hours to resolve.
