### ISSUE TITLE
Update README.MD

### ISSUE THREAD

**Issue by aleemont** [NoiSek/Aether#93]
**Expected behavior**
Links provided for manual installation no longer working

**Actual behavior**
`git clone git@github.com:NoiSek/Aether.git
Cloning into 'Aether'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.`

`git clone https://github.com/NoiSek/Aether/releases/latest
Cloning into 'latest'...
remote: Not Found
fatal: repository 'https://github.com/NoiSek/Aether/releases/latest`

**Additional context**
O.S: Arch Linux

**Comment by NoiSek** [comment]
The error you see is caused by a failure to authenticate using your local SSH keys, meaning that something isn't configured properly or that you don't have a set of public / private keys for Git to use.

To clone via https, you would instead clone from: `https://github.com/NoiSek/Aether.git`

Otherwise, you can fix that issue by following this process: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh

As you've probably already discovered, you can also download the source code directly to accomplish the same thing from either of these two locations:
- https://github.com/NoiSek/Aether/releases
- https://github.com/NoiSek/Aether/archive/master.zip
